version: 2

project_name: release-tools

builds:
  - id: release-tools
    main: ./cmd/release-tools
    binary: release-tools
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.releaseToolsVersion={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - id: binaries
    ids:
      - release-tools
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

gitea_urls:
  api: https://codeberg.org/api/v1
  download: https://codeberg.org

release:
  gitea:
    owner: rch
    name: release-tools
  mode: replace
